import 'package:flutter_test/flutter_test.dart';
import 'package:all_in_one/models/dynamic_floor_model.dart';
import 'package:all_in_one/services/architectural_prompt_service.dart';
import 'package:all_in_one/widgets/blueprint_canvas/dynamic_floor_2d_painter.dart';
import 'package:all_in_one/services/cad_hover_hit_test_service.dart';
import 'package:all_in_one/services/blueprint_export_service.dart';
import 'package:all_in_one/services/design_option_manager_service.dart';
import 'package:flutter/material.dart';

void main() {
  group('Recalibrate Shared Wall & Margin Tests', () {
    test('Adding Wardrobe and Bed on North Wall recalibrates spans flush without forced margins', () {
      final dims = DynamicFloorDimensions(roomWidth: 10.0, roomLength: 14.0);
      final placements = [
        RoomItemPlacement(id: '1', itemName: 'Wardrobe', targetWall: 'North Wall (N)'),
        RoomItemPlacement(id: '2', itemName: 'King Bed', targetWall: 'North Wall (N)'),
      ];

      final items = ArchitecturalPromptService.calculateDimensions(
        dims: dims,
        placements: placements,
      );

      expect(items.length, 2);
      expect(items[0].itemName, 'Wardrobe');
      expect(items[1].itemName, 'King Bed');

      // Check rects generated by DynamicFloor2DPainter
      final rectMap = DynamicFloor2DPainter.calculateItemRects(
        dims: dims,
        items: items,
        canvasSize: const Size(950, 750),
        scale: 28.0,
      );

      final r1 = rectMap['1']!;
      final r2 = rectMap['2']!;

      // Items should be adjacent along North Wall without overlapping
      expect(r1.right <= r2.left + 0.1 || r2.right <= r1.left + 0.1, isTrue);
    });

    test('Full wall wardrobe occupies 100% of wall span', () {
      final dims = DynamicFloorDimensions(roomWidth: 10.0);
      final placements = [
        RoomItemPlacement(id: 'w1', itemName: 'Wardrobe full wall', targetWall: 'North Wall (N)'),
      ];

      final items = ArchitecturalPromptService.calculateDimensions(
        dims: dims,
        placements: placements,
      );

      expect(items.length, 1);
      expect(items[0].length, closeTo(10.0, 0.05));
    });

    test('Custom drag positions are respected in rect calculation without forced margin offset', () {
      final dims = DynamicFloorDimensions();
      final placements = [
        RoomItemPlacement(
          id: 'custom_bed',
          itemName: 'Bed',
          targetWall: 'Center Floor',
          customPosX: 3.5,
          customPosY: 5.0,
          customWidth: 5.0,
          customLength: 6.5,
        ),
      ];

      final items = ArchitecturalPromptService.calculateDimensions(
        dims: dims,
        placements: placements,
      );

      final origin = DynamicFloor2DPainter.getOrigin(
        dims: dims,
        canvasSize: const Size(950, 750),
        scale: 28.0,
      );

      final rectMap = DynamicFloor2DPainter.calculateItemRects(
        dims: dims,
        items: items,
        canvasSize: const Size(950, 750),
        scale: 28.0,
      );

      final r = rectMap['custom_bed']!;
      expect(r.left, closeTo(origin.dx + 3.5 * 28.0, 0.1));
      expect(r.top, closeTo(origin.dy + 5.0 * 28.0, 0.1));
      expect(r.width, closeTo(5.0 * 28.0, 0.1));
      expect(r.height, closeTo(6.5 * 28.0, 0.1));
    });

    test('Stretching breadth (East) and length (North) updates dimensions accurately without limit', () {
      final dims = DynamicFloorDimensions(roomWidth: 12.0, roomLength: 16.0);
      final placement = RoomItemPlacement(
        id: 'wardrobe_1',
        itemName: 'Wardrobe',
        targetWall: 'North Wall (N)',
        customPosX: 2.0,
        customPosY: 3.0,
        customWidth: 2.5,
        customLength: 4.5,
      );

      // Stretch breadth (X-span) towards East by +2.0 ft
      placement.customWidth = placement.customWidth! + 2.0; // Now 4.5 ft
      expect(placement.customWidth, 4.5);

      // Stretch length (Y-span) towards North by +3.0 ft
      placement.customLength = placement.customLength! + 3.0; // Now 7.5 ft
      expect(placement.customLength, 7.5);

      final items = ArchitecturalPromptService.calculateDimensions(
        dims: dims,
        placements: [placement],
      );

      expect(items[0].width, 4.5);
      expect(items[0].length, 7.5);

      // 4-wall clearances:
      // gapWest = 2.0 ft
      // gapEast = 12.0 - (2.0 + 4.5) = 5.5 ft
      // gapSouth = 3.0 ft
      // gapNorth = 16.0 - (3.0 + 7.5) = 5.5 ft
      final prompt = ArchitecturalPromptService.generateMasterPrompt(
        dims: dims,
        placements: [placement],
      );

      expect(prompt.contains("Wall Gaps: W (Left): 2.00', E (Right): 5.50', S (Top): 3.00', N (Bottom): 5.50'"), isTrue);
    });

    test('Wardrobe moved to South Wall has exactly 0.00 margin (Flush) and strict independence', () {
      final dims = DynamicFloorDimensions(roomWidth: 10.5, roomLength: 12.0);
      final wardrobe = RoomItemPlacement(
        id: 'wardrobe_south',
        itemName: 'Wardrobe Run',
        targetWall: 'South Wall (S)',
        customPosX: 0.0,
        customPosY: 0.0, // 0 margin on South wall!
        customWidth: 10.5, // Spans full breadth across East-West
        customLength: 2.0, // Depth
      );

      final items = ArchitecturalPromptService.calculateDimensions(
        dims: dims,
        placements: [wardrobe],
      );

      const canvasSize = Size(950, 750);
      const scale = 28.0;
      final origin = DynamicFloor2DPainter.getOrigin(dims: dims, canvasSize: canvasSize, scale: scale);
      final rectMap = DynamicFloor2DPainter.calculateItemRects(
        dims: dims,
        items: items,
        canvasSize: canvasSize,
        scale: scale,
      );

      final rect = rectMap['wardrobe_south']!;
      expect(rect.top, origin.dy); // Exactly flush with South wall
      expect(rect.left, origin.dx); // Exactly flush with West wall
      expect(rect.right, origin.dx + 10.5 * scale); // Exactly flush with East wall

      // Verify clearance from South wall is exactly 0.00'
      final topGap = (rect.top - origin.dy) / scale;
      final leftGap = (rect.left - origin.dx) / scale;
      final rightGap = ((origin.dx + dims.roomWidth * scale) - rect.right) / scale;
      final bottomGap = ((origin.dy + dims.roomLength * scale) - rect.bottom) / scale;

      expect(topGap, 0.0);
      expect(leftGap, 0.0);
      expect(rightGap, 0.0);
      expect(bottomGap, 10.0); // 12.0 - 2.0 = 10.0 ft clearance to North wall
    });

    test('Dragging South/North handles modifies ONLY Length without altering Breadth', () {
      final baseW = 10.25;
      final baseL = 1.14;
      double curW = baseW;
      double curL = baseL;

      // Simulate dragging South handle (top edge) upwards by -1.0 ft (expanding length towards South)
      final deltaY = -1.0;
      final maxTop = 2.14;
      final clampY = deltaY.clamp(-maxTop, baseL - 0.5);
      curL = (baseL - clampY).clamp(0.5, 12.0);
      curW = baseW; // Strict Invariant: Breadth untouched!

      expect(curL, closeTo(2.14, 0.01));
      expect(curW, 10.25); // Breadth remains 100% unchanged

      // Simulate dragging East handle (right edge) by +1.5 ft (expanding breadth towards East)
      final deltaX = 1.5;
      curW = (baseW + deltaX).clamp(0.5, 12.0);
      curL = 2.14; // Strict Invariant: Length untouched!

      expect(curW, closeTo(11.75, 0.01));
      expect(curL, 2.14); // Length remains 100% unchanged
    });
  });

  group('Hover Inspection Hit-Testing Tests', () {
    test('Hovering on a placed furniture item returns detailed CAD inspection metadata', () {
      final dims = DynamicFloorDimensions(roomWidth: 12.0, roomLength: 16.0);
      final placement = RoomItemPlacement(
        id: 'king_bed_1',
        itemName: 'King Size Bed',
        targetWall: 'West Wall (W)',
        customPosX: 2.0,
        customPosY: 3.0,
        customWidth: 5.5,
        customLength: 6.5,
      );

      final items = ArchitecturalPromptService.calculateDimensions(
        dims: dims,
        placements: [placement],
      );

      const canvasSize = Size(950, 750);
      const scale = 28.0;
      final origin = DynamicFloor2DPainter.getOrigin(dims: dims, canvasSize: canvasSize, scale: scale);

      // Mouse is over the King Bed center
      final bedCenter = Offset(origin.dx + (2.0 + 2.75) * scale, origin.dy + (3.0 + 3.25) * scale);

      final detail = CadHoverHitTestService.hitTest(
        localPos: bedCenter,
        dims: dims,
        items: items,
        selectedItemId: null,
        canvasSize: canvasSize,
        scale: scale,
      );

      expect(detail, isNotNull);
      expect(detail!.title, 'King Size Bed');
      expect(detail.category, 'FURNITURE ITEM');
      expect(detail.keyMetrics['Width (W-E)'], "5.50'");
      expect(detail.keyMetrics['Length (S-N)'], "6.50'");
      expect(detail.wallClearances?['West (Left)'], "2.00'");
      expect(detail.wallClearances?['East (Right)'], "4.50'"); // 12 - (2 + 5.5) = 4.5
      expect(detail.wallClearances?['South (Top)'], "3.00'");
      expect(detail.wallClearances?['North (Bottom)'], "6.50'"); // 16 - (3 + 6.5) = 6.5
    });

    test('Hovering on room zones returns architectural specs and area', () {
      final dims = DynamicFloorDimensions();
      const canvasSize = Size(950, 750);
      const scale = 28.0;
      final origin = DynamicFloor2DPainter.getOrigin(dims: dims, canvasSize: canvasSize, scale: scale);

      // Mouse over Modular Kitchen
      final kitchenCenter = Offset(origin.dx + (dims.roomWidth + dims.kitchenWidth / 2) * scale, origin.dy + (dims.kitchenLength / 2) * scale);
      final kDetail = CadHoverHitTestService.hitTest(
        localPos: kitchenCenter,
        dims: dims,
        items: [],
        selectedItemId: null,
        canvasSize: canvasSize,
        scale: scale,
      );

      expect(kDetail, isNotNull);
      expect(kDetail!.title, 'Modular Kitchen & Pantry');
      expect(kDetail.category, 'ROOM ZONE');
      expect(kDetail.keyMetrics.containsKey('Carpet Area'), isTrue);

      // Mouse over Ensuite Bathroom
      final bathCenter = Offset(origin.dx + (dims.bathWidth / 2) * scale, origin.dy + dims.roomLength * scale);
      final bDetail = CadHoverHitTestService.hitTest(
        localPos: bathCenter,
        dims: dims,
        items: [],
        selectedItemId: null,
        canvasSize: canvasSize,
        scale: scale,
      );

      expect(bDetail, isNotNull);
      expect(bDetail!.title, 'Ensuite Bathroom Suite');
      expect(bDetail.category, 'ROOM ZONE');
    });

    test('Hovering on door openings returns radial arc dimensions and clearance notes', () {
      final dims = DynamicFloorDimensions();
      const canvasSize = Size(950, 750);
      const scale = 28.0;
      final origin = DynamicFloor2DPainter.getOrigin(dims: dims, canvasSize: canvasSize, scale: scale);

      // Hover on Master Bedroom Door at end of East Wall (y = 18.50 ft)
      final roomDoorPivot = Offset(origin.dx + dims.roomWidth * scale, origin.dy + dims.roomLength * scale);
      final doorDetail = CadHoverHitTestService.hitTest(
        localPos: roomDoorPivot + const Offset(-10, -10),
        dims: dims,
        items: [],
        selectedItemId: null,
        canvasSize: canvasSize,
        scale: scale,
      );

      expect(doorDetail, isNotNull);
      expect(doorDetail!.category, 'OPENING & EGRESS');
      expect(doorDetail.title, 'Master Bedroom Door');

      // Hover on Ensuite Bathroom Gate on Top Partition Wall
      final bathDoorPivot = Offset(origin.dx + dims.bathWidth * scale, origin.dy + (dims.roomLength - dims.bathLength / 2) * scale);
      final bathDetail = CadHoverHitTestService.hitTest(
        localPos: bathDoorPivot + const Offset(-10, 4),
        dims: dims,
        items: [],
        selectedItemId: null,
        canvasSize: canvasSize,
        scale: scale,
      );

      expect(bathDetail, isNotNull);
      expect(bathDetail!.category, 'OPENING & EGRESS');
      expect(bathDetail.title, 'Ensuite Bathroom Gate');
    });
  });

  group('Unit Conversion (cm, m, feet, inches) Tests', () {
    test('DynamicFloorDimensions.convertValue converts accurately between all 4 units', () {
      // 10 feet to meters: 10 * 0.3048 = 3.048 m
      expect(DynamicFloorDimensions.convertValue(10.0, DimensionUnit.feet, DimensionUnit.meters), closeTo(3.048, 0.001));

      // 3.048 meters to feet: 10.0 ft
      expect(DynamicFloorDimensions.convertValue(3.048, DimensionUnit.meters, DimensionUnit.feet), closeTo(10.0, 0.001));

      // 1 foot to inches: 12 inches
      expect(DynamicFloorDimensions.convertValue(1.0, DimensionUnit.feet, DimensionUnit.inches), closeTo(12.0, 0.001));

      // 100 cm to meters: 1.0 m
      expect(DynamicFloorDimensions.convertValue(100.0, DimensionUnit.centimeters, DimensionUnit.meters), closeTo(1.0, 0.001));

      // 1 meter to centimeters: 100.0 cm
      expect(DynamicFloorDimensions.convertValue(1.0, DimensionUnit.meters, DimensionUnit.centimeters), closeTo(100.0, 0.001));

      // 12 inches to cm: 12 * 2.54 = 30.48 cm
      expect(DynamicFloorDimensions.convertValue(12.0, DimensionUnit.inches, DimensionUnit.centimeters), closeTo(30.48, 0.001));
    });

    test('Switching DynamicFloorDimensions unit updates all room dimensions and formatting', () {
      final dims = DynamicFloorDimensions(
        roomWidth: 10.0,
        roomLength: 15.0,
        unit: DimensionUnit.feet,
      );

      expect(dims.format(dims.roomWidth), "10.00'");
      expect(dims.formatArea(dims.roomWidth * dims.roomLength), "150.0 sq.ft");

      // Switch to meters
      dims.switchUnit(DimensionUnit.meters);
      expect(dims.unit, DimensionUnit.meters);
      expect(dims.roomWidth, closeTo(3.048, 0.01));
      expect(dims.roomLength, closeTo(4.572, 0.01));
      expect(dims.format(dims.roomWidth), contains("m"));
      expect(dims.formatArea(dims.roomWidth * dims.roomLength), contains("m²"));

      // Switch to centimeters
      dims.switchUnit(DimensionUnit.centimeters);
      expect(dims.unit, DimensionUnit.centimeters);
      expect(dims.roomWidth, closeTo(304.8, 0.5));
      expect(dims.format(dims.roomWidth), contains("cm"));
      expect(dims.formatArea(dims.roomWidth * dims.roomLength), contains("cm²"));

      // Switch to inches
      dims.switchUnit(DimensionUnit.inches);
      expect(dims.unit, DimensionUnit.inches);
      expect(dims.roomWidth, closeTo(120.0, 0.5));
      expect(dims.format(dims.roomWidth), contains('"'));
      expect(dims.formatArea(dims.roomWidth * dims.roomLength), contains("sq.in"));
    });

    test('Hover inspection and architectural prompt reflect unit changes dynamically', () {
      final dims = DynamicFloorDimensions(
        roomWidth: 10.0,
        roomLength: 15.0,
        unit: DimensionUnit.meters,
      );

      final placement = RoomItemPlacement(
        id: 'wardrobe_m',
        itemName: 'Wardrobe',
        targetWall: 'North Wall (N)',
        customPosX: 1.0,
        customPosY: 1.0,
        customWidth: 1.2,
        customLength: 2.0,
      );

      final items = ArchitecturalPromptService.calculateDimensions(
        dims: dims,
        placements: [placement],
      );

      final prompt = ArchitecturalPromptService.generateMasterPrompt(
        dims: dims,
        placements: [placement],
      );

      expect(prompt.contains('**Measurement Standard:** Meters (m)'), isTrue);
      expect(prompt.contains('1.20 m'), isTrue);

      final scale = DynamicFloorDimensions.getBaseScale(dims.unit);
      final origin = DynamicFloor2DPainter.getOrigin(
        dims: dims,
        canvasSize: const Size(950, 750),
        scale: scale,
      );

      final itemCenter = Offset(origin.dx + (1.0 + 0.6) * scale, origin.dy + (1.0 + 1.0) * scale);
      final detail = CadHoverHitTestService.hitTest(
        localPos: itemCenter,
        dims: dims,
        items: items,
        selectedItemId: null,
        canvasSize: const Size(950, 750),
        scale: scale,
      );

      expect(detail, isNotNull);
      expect(detail!.keyMetrics['Width (W-E)'], contains('m'));
      expect(detail.wallClearances?['West (Left)'], contains('m'));
    });
  });

  group('Ultra High-Resolution 4K Blueprint Export Tests', () {
    testWidgets('BlueprintExportService generates valid 4K PNG with left schedule specifications', (tester) async {
      final dims = DynamicFloorDimensions(
        roomWidth: 12.0,
        roomLength: 16.0,
        unit: DimensionUnit.feet,
      );

      final placement = RoomItemPlacement(
        id: 'king_bed_export',
        itemName: 'King Size Bed',
        targetWall: 'West Wall (W)',
        customPosX: 2.0,
        customPosY: 3.0,
        customWidth: 6.0,
        customLength: 6.5,
      );

      final items = ArchitecturalPromptService.calculateDimensions(
        dims: dims,
        placements: [placement],
      );

      await tester.runAsync(() async {
        final pngBytes = await BlueprintExportService.generateUltraHighResBlueprintSheet(
          dims: dims,
          items: items,
          roomName: 'Master Bedroom Suite CAD',
          sheetWidth: 1280.0,
          sheetHeight: 800.0,
        );

        expect(pngBytes, isNotNull);
        expect(pngBytes!.isNotEmpty, isTrue);

        // Verify PNG magic header bytes: 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A
        expect(pngBytes[0], 0x89);
        expect(pngBytes[1], 0x50); // 'P'
        expect(pngBytes[2], 0x4E); // 'N'
        expect(pngBytes[3], 0x47); // 'G'

        // Large PNG data size (> 20KB)
        expect(pngBytes.lengthInBytes > 20000, isTrue);
      });
    });
  });

  group('Design Color Contrast & Single Color per Item Palette Tests', () {
    test('DynamicFloor2DPainter.getItemColor provides distinct single color for each furniture item type', () {
      final bedColor = DynamicFloor2DPainter.getItemColor('bed_1', 'King Bed');
      final wardrobeColor = DynamicFloor2DPainter.getItemColor('ward_1', 'Full Wardrobe');
      final tvColor = DynamicFloor2DPainter.getItemColor('tv_1', 'TV Media Unit');
      final dressingColor = DynamicFloor2DPainter.getItemColor('dress_1', 'Dressing Vanity');
      final studyColor = DynamicFloor2DPainter.getItemColor('study_1', 'Study Desk');
      final sofaColor = DynamicFloor2DPainter.getItemColor('sofa_1', 'Living Sofa');
      final diningColor = DynamicFloor2DPainter.getItemColor('bar_1', 'Dining Table');

      // Verify specific architectural palettes
      expect(bedColor, const Color(0xFF2563EB)); // Royal Blue
      expect(wardrobeColor, const Color(0xFF059669)); // Emerald Green
      expect(tvColor, const Color(0xFF7C3AED)); // Deep Violet
      expect(dressingColor, const Color(0xFFE11D48)); // Rose Pink
      expect(studyColor, const Color(0xFFD97706)); // Amber Orange
      expect(sofaColor, const Color(0xFF0891B2)); // Cyan Teal
      expect(diningColor, const Color(0xFFDC2626)); // Crimson Red

      // Verify that every distinct item type has its own single dedicated color
      final Set<Color> uniqueColors = {
        bedColor,
        wardrobeColor,
        tvColor,
        dressingColor,
        studyColor,
        sofaColor,
        diningColor,
      };
      expect(uniqueColors.length, 7, reason: 'Every item type must have a distinct dedicated color');
    });

    test('CadHoverHitTestService returns yellow accent for door/gate openings', () {
      final dims = DynamicFloorDimensions();
      const canvasSize = Size(950, 750);
      const scale = 28.0;
      final origin = DynamicFloor2DPainter.getOrigin(dims: dims, canvasSize: canvasSize, scale: scale);

      // Egress Door on Master Bedroom East Wall End
      final doorPivot = Offset(origin.dx + dims.roomWidth * scale, origin.dy + dims.roomLength * scale);
      final doorHit = CadHoverHitTestService.hitTest(
        localPos: doorPivot + const Offset(-10, -10),
        dims: dims,
        items: [],
        selectedItemId: null,
        canvasSize: canvasSize,
        scale: scale,
      );
      expect(doorHit, isNotNull);
      expect(doorHit!.accentColor, const Color(0xFFEAB308)); // Yellow Gate/Door
    });
  });

  group('Architectural Design Options (Save, Finalize, Add New, Copy & Branch) Tests', () {
    test('DesignOptionManagerService initializes with default design options', () {
      final allDesigns = DesignOptionManagerService.designs;
      expect(allDesigns.isNotEmpty, isTrue);
      expect(allDesigns.length >= 2, isTrue);

      final active = DesignOptionManagerService.activeDesign;
      expect(active.id, 'option_a_standard');
      expect(active.name.contains('Option A'), isTrue);
      expect(active.isFinalized, isFalse);
    });

    test('Creating a brand new design option adds it to the designs list and makes it active', () {
      final initialCount = DesignOptionManagerService.designs.length;
      final customDims = DynamicFloorDimensions(roomWidth: 14.0, roomLength: 20.0);

      final newDesign = DesignOptionManagerService.createNewDesignOption(
        name: 'Option D: Luxury Penthouse',
        description: 'Spacious 14x20 master suite',
        dims: customDims,
        initialPlacements: [
          RoomItemPlacement(
            id: 'penthouse_bed',
            itemName: 'King Bed Luxury',
            targetWall: 'West Wall (W)',
            customPosX: 1.0,
            customPosY: 4.0,
            customWidth: 7.0,
            customLength: 6.5,
          ),
        ],
      );

      expect(DesignOptionManagerService.designs.length, initialCount + 1);
      expect(DesignOptionManagerService.activeDesignId, newDesign.id);
      expect(DesignOptionManagerService.activeDesign.name, 'Option D: Luxury Penthouse');
      expect(DesignOptionManagerService.activeDesign.dims.roomWidth, 14.0);
      expect(DesignOptionManagerService.activeDesign.placements.length, 1);
    });

    test('Copying/duplicating an old design option allows modifying the copy without altering the original', () {
      // 1. Source design
      final original = DesignOptionManagerService.designs.first;
      final originalBedCount = original.placements.length;
      final originalWidth = original.dims.roomWidth;

      // 2. Duplicate to new design
      final duplicated = DesignOptionManagerService.duplicateDesignOption(
        original.id,
        newName: 'Option A (Custom Alteration)',
        newDescription: 'Cloned and modified with extra study table',
      );

      expect(duplicated.id != original.id, isTrue);
      expect(duplicated.name, 'Option A (Custom Alteration)');
      expect(DesignOptionManagerService.activeDesignId, duplicated.id);

      // 3. Modify the duplicated design's dimensions and add items
      final modDims = duplicated.dims.clone()..roomWidth = 16.0;
      final modPlacements = List<RoomItemPlacement>.from(duplicated.placements)
        ..add(RoomItemPlacement(
          id: 'custom_study_table_new',
          itemName: 'Study Table Added in Copy',
          targetWall: 'North Wall (N)',
          customPosX: 2.0,
          customPosY: 14.0,
          customWidth: 5.0,
          customLength: 2.5,
        ));

      // 4. Save changes to duplicated design
      final savedCopy = DesignOptionManagerService.saveCurrentDesign(
        dims: modDims,
        placements: modPlacements,
      );

      expect(savedCopy.dims.roomWidth, 16.0);
      expect(savedCopy.placements.length, originalBedCount + 1);

      // 5. Verify the ORIGINAL design was NOT changed
      final refreshedOriginal = DesignOptionManagerService.designs.firstWhere((d) => d.id == original.id);
      expect(refreshedOriginal.dims.roomWidth, originalWidth);
      expect(refreshedOriginal.placements.length, originalBedCount);
    });

    test('Finalizing a design marks it as approved with certification timestamp & notes', () {
      final active = DesignOptionManagerService.activeDesign;
      expect(active.isFinalized, isFalse);

      final finalized = DesignOptionManagerService.finalizeDesign(
        active.id,
        approvalNotes: 'Approved by Senior Architect on site.',
      );

      expect(finalized.isFinalized, isTrue);
      expect(finalized.finalizedAt, isNotNull);
      expect(finalized.finalizedNotes, 'Approved by Senior Architect on site.');

      // Unlocking returns to draft
      final reopened = DesignOptionManagerService.unlockFinalizedDesign(active.id);
      expect(reopened.isFinalized, isFalse);
    });
  });

  group('Item Floor Color & Door Cyclic Rotation Tests', () {
    test('Each item category has a distinct vibrant floor occupancy color', () {
      final bedColor = DynamicFloor2DPainter.getItemColor('item1', 'King Bed');
      final wardrobeColor = DynamicFloor2DPainter.getItemColor('item2', 'Sliding Wardrobe');
      final tvColor = DynamicFloor2DPainter.getItemColor('item3', 'TV Media Unit');
      final vanityColor = DynamicFloor2DPainter.getItemColor('item4', 'Dressing Vanity');
      final deskColor = DynamicFloor2DPainter.getItemColor('item5', 'Study Work Table');
      final sofaColor = DynamicFloor2DPainter.getItemColor('item6', 'Lounge Sofa');

      expect(bedColor, const Color(0xFF2563EB)); // Royal Blue
      expect(wardrobeColor, const Color(0xFF059669)); // Emerald Green
      expect(tvColor, const Color(0xFF7C3AED)); // Deep Violet
      expect(vanityColor, const Color(0xFFE11D48)); // Rose Pink
      expect(deskColor, const Color(0xFFD97706)); // Amber Orange
      expect(sofaColor, const Color(0xFF0891B2)); // Cyan Teal
    });

    test('Room door is hinged on East dividing wall at opposite/South tip and supports cyclic 4-quadrant rotation', () {
      final dims = DynamicFloorDimensions(roomWidth: 10.0, roomLength: 14.0);
      expect(dims.roomDoorSwingQuadrant, 0);

      // Cycle quadrant 1
      dims.roomDoorSwingQuadrant = (dims.roomDoorSwingQuadrant + 1) % 4;
      expect(dims.roomDoorSwingQuadrant, 1);

      // Cycle quadrant 2
      dims.roomDoorSwingQuadrant = (dims.roomDoorSwingQuadrant + 1) % 4;
      expect(dims.roomDoorSwingQuadrant, 2);

      // Cycle quadrant 3
      dims.roomDoorSwingQuadrant = (dims.roomDoorSwingQuadrant + 1) % 4;
      expect(dims.roomDoorSwingQuadrant, 3);

      // Cycle quadrant 4 (loops back to 0)
      dims.roomDoorSwingQuadrant = (dims.roomDoorSwingQuadrant + 1) % 4;
      expect(dims.roomDoorSwingQuadrant, 0);

      // Test clone preserves roomDoorSwingQuadrant
      dims.roomDoorSwingQuadrant = 2;
      final cloned = dims.clone();
      expect(cloned.roomDoorSwingQuadrant, 2);
    });

    test('Selected item dimension, position, and rotation can be freely updated', () {
      final placement = RoomItemPlacement(
        id: 'bed_test',
        itemName: 'King Bed',
        targetWall: 'North Wall (N)',
        customWidth: 6.0,
        customLength: 6.5,
        customPosX: 2.0,
        customPosY: 0.0,
        rotationDegrees: 0,
      );

      // Change breadth & length
      placement.customWidth = 6.5;
      placement.customLength = 7.0;
      expect(placement.customWidth, 6.5);
      expect(placement.customLength, 7.0);

      // Change position
      placement.customPosX = 3.0;
      placement.customPosY = 1.5;
      expect(placement.customPosX, 3.0);
      expect(placement.customPosY, 1.5);

      // Rotate 90 degrees
      placement.rotationDegrees = (placement.rotationDegrees + 90) % 360;
      expect(placement.rotationDegrees, 90);
      placement.rotationDegrees = (placement.rotationDegrees + 90) % 360;
      expect(placement.rotationDegrees, 180);
    });
  });
}

